model: model.dgn.ecgmm.ECGMM
experiment: experiment.cgmm_embedding_task.EmbeddingCGMMTask
higher_results_are_better: True
dataset-getter: data.provider.IncrementalDataProvider
log_every: 1
num_dataloader_workers: 2  # > 0 only with --debug option and GPU device
pin_memory: True  # True only with --debug option and GPU device
device: cuda
grid:
  layer_config:
    embeddings_folder: /data/errica/ECGMM_EMBEDDINGS
    checkpoint: True
    batch_size:
      - 32
    shuffle:
      - False
    previous_layers_to_use:
      - "1"  # multiple layers: "1,2,4"
    concatenate_on_axis: 1  # must be > 0
    max_layers:
      - 20
    C:
      - 20
    A: 1
    predictor: null
    node_predictor:
      - model.predictor.node_predictor.UnsupervisedProbabilisticNodeReadout
    node_emission:
      - model.distribution.emission.Categorical
    edge_predictor:
      - model.predictor.node_predictor.UnsupervisedProbabilisticNodeReadout
    edge_emission:
      - model.distribution.emission.Categorical
    # LEAVE UNIBIGRAM TRUE: unigrams will be automatically generated by EmbeddingCGMMTask
    unibigram:
       - True
    aggregation:
      - mean
    infer_with_posterior:
      - False
      - True
    epochs:
      - 20
    wrapper:
      - training.engine.IncrementalTrainingEngine
    loss:
      - training.callback.loss.CGMMLoss
    optimizer:
      - training.callback.optimizer.CGMMOptimizer
    scorer:
      -
        class_name: training.callback.score.MultiScore
        args:
           # used at model selection time. Should be the one on which to perform early stopping
           main_scorer: training.callback.score.CGMMCompleteLikelihoodScore
           true_likelihood: training.callback.score.CGMMTrueLikelihoodScore
    plotter:
      - training.callback.plotter.Plotter
