splitter:
  root: ECGMM_SPLITS/
  class_name: data.splitter.Splitter
  args:
    n_outer_folds: 10
    n_inner_folds: 1
    seed: 42
    stratify: False
    shuffle: True
    val_ratio: 0.1
    test_ratio: 0.1
dataset:
  root: DATA/
  class_name: data.dataset.QM7bCGMMDiscretizedInterface
  args:
    root: DATA/QM7bCGMMDiscretized
    name: QM7bCGMMDiscretized
