splitter:
  root: ECGMM_SPLITS/
  class_name: data.splitter.Splitter
  args:
    n_outer_folds: 10
    n_inner_folds: 1
    seed: 42
    stratify: False
    shuffle: True
    val_ratio: 0.1
    test_ratio: 0.1
dataset:
  root: DATA/
  class_name: data.dataset.QM7bECGMMInterface
  args:
    root: DATA/QM7bECGMM
    name: QM7bECGMM
  # useful for social datasets with no node features
  transforms:
      - class_name: data.transform.ConstantIfEmpty
        args:
          value: 0
