splitter:
  root: ECGMM_SPLITS/
  class_name: data.splitter.Splitter
  args:
    n_outer_folds: 10
    n_inner_folds: 1
    seed: 42
    stratify: True  # works for graph classification tasks
    shuffle: True
    val_ratio: 0.1
    test_ratio: 0.1
dataset:
  root: DATA/
  class_name: data.dataset.TUDataset
  args:
    root: DATA/
    name: NCI1
